---
- name: Replace IP address in ossec.conf using sed
  hosts: localhost
  tasks:
    - name: Replace IP address using sed
      become: yes
      replace:
        path: /var/ossec/etc/ossec.conf
        regexp: '^(.*)10\.10\.8\.32(.*)$'
        replace: '\110.10.2.24\2'
        backup: yes
